### ISSUE TITLE
Add coordinate space measurement method

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/ldd-geom#2]
Under <Coordinate_Space_Definition> add:

  <measurement_method> -  Specifies the method by which the coordinate space was measured.  This provides an indication of the quality of the definition.
cardinality: 0..1
Valids will increase over time.  Start with:  Unknown, Tilt_Only, Sun_Find, Bundle_Adjustment

**Comment by thareUSGS** [comment]
thank you. Updated and closed per https://github.com/pds-data-dictionaries/ldd-geom/pull/4
